#!/usr/bin/env python3

#abandoned - cut down to rpm2cpio, rest is just research
#rpm are based on libsolv to manipulate

import struct

def readsection(a,b,c):
    top=b
    magic=bytes([0x8e,0xad,0xe8])
    if a[b:b+3]!=magic:
        return 0
    entry,store=struct.unpack('!2I',a[b+8:b+8+8]) #skip magic:reserved
    print('{:02X}'.format(b),entry,store)
    b+=16
    z={}
    for x in range(entry):
        tag,typ,off,cnt=struct.unpack('!4I',a[b:b+16])
        i=z.setdefault(off,{})
        i['tag']=tag
        i['typ']=typ
        if typ==7:
            i['size']=cnt>>2
        elif typ==4:
            i['size']=cnt
        elif typ==6:
            i['size']=11
        print('>>',tag,typ,off,cnt,top+off+(entry+1)*16)
        b+=16
    skip=0
    for x in sorted(z.keys()):
        sz=z[x]['size']
        p=struct.unpack('!{}I'.format(sz),a[b+x:b+x+sz*4])
        if z[x]['size']>4:
            p='{:08X} ...'.format(p[0])
        else:
            if z[x]['tag']==1004:
                p=' '.join(map(lambda j:'{:08X}'.format(j),p))
            elif z[x]['tag']==269:
                p=' '.join(map(lambda j:'{:08X}'.format(j),p[0:10]))
            if sz==1:
                p=p[0]
        print('\t'.join(map(lambda j:str(j),[
            '{:04X}'.format(x),
            c[z[x]['tag']],
            z[x]['typ'],
            x,
            z[x]['size'],
            b+x,
            p
            ])))
        skip+=sz
    #oldheader(96)+sigentryheader(16)+sigentryCount*16 at this 
    #point the sig entry 'size' refers to size of file without
    #old header and sigheader. also where the md5 is taken for
    if skip*4==store:
        b+=skip*4
        b+=(-b)&7
        return b
    return 0

#http://ftp.rpm.org/api/4.14.0/group__rpmtag.html
rpmsigtag={
    62:'hs',     # RPMTAG_HEADERSIGNATURES
    268:'rsah', #256+12 =RPMTAG_RSAHEADER
    269:'sha1h',#256+13 =RPMTAG_SHA1HEADER  +17=SHA256
    1000:'size',
    1001:'ver',
    1002:'rsa', #pgp RPMTAG_RELEASE
    1004:'md5', # RPMTAG_SUMMARY
    1005:'dsa', #gpg RPMTAG_DESCRIPTION
    1007:'build?',  # RPMTAG_BUILDHOST
}
rpmtag={
    1000:'name',    #6
    1001:'ver',     #6
    1002:'pl',      #6
    1004:'descr',   #9
    1005:'summ',    #9
    1006:'date?',   #4
    1007:'build',   #6
    1010:'dist',    #6
    1011:'vend',    #6
    1014:'asl?',    #6
    1015:'bug?',    #6
}
with open('httpd-2.4.6-31.ael7b_1.1.src.rpm','rb') as t:
    k=t.read()

t=0x60
t=readsection(k,t,rpmsigtag);print('@',t)
t=readsection(k,t,rpmtag);print('@',t)
