#!/usr/bin/env python3

import curses
import requests
import os
import sys
import functools

class sehchain(object):
    def __init__(self,ex):
        self.__echain=[]
        self.__cchain=[]
        if isinstance(ex,Exception):
            p=ex
        else:
            p=sys.exc_info()[1]
        while p.__context__:
            self.__echain.insert(0,'{}.{}'.format(p.__context__.__module__,p.__context__.__class__.__name__))
            self.__cchain.insert(0,p.__context__)
            p=p.__context__

    def __iter__(self):
        return iter(self.__echain)

def invoke(display,roku,action):
    retry=5
    url='http://{}:8060/keypress/{}'.format(roku,action)
    while retry:
        try:
            r=requests.post(url,data={},timeout=3)
        except requests.exceptions.ConnectionError as e:
            check=sehchain(e)
            if 'socket.gaierror' in check:
                retry=0
            else:
                raise
        else:
            if r.status_code in (200,202):
                return True
            retry-=1
    return False

def menu(display):
    display.addstr(8,20, '(`) home             (u) +                   <up>      ')
    display.addstr(9,20, '(z) select  (h) rew  (j) -     (k) >>   <left>  <right>')
    display.addstr(10,20,'<tab> back           (m) mute               <down>     ')
    display.addstr(11,20,'<esc> exit          <space> play/pause   <enter> enter ')

def main(target,display):
    remap={
        ord(' '):'play',
        ord('u'):'volumeup',
        ord('j'):'volumedown',
        ord('m'):'volumemute',
        ord('h'):'rev',
        ord('k'):'fwd',
        ord('z'):'select',
        ord('	'):'back',
        ord('`'):'home',
        10:'enter',
        127:'backspace',
        curses.KEY_LEFT:'left',
        curses.KEY_RIGHT:'right',
        curses.KEY_UP:'up',
        curses.KEY_DOWN:'down',
        }
    display.keypad(True)
    curses.curs_set(False)
    display.clear()
    menu(display)
    try:
        x=y=0
        while True:
            k=display.getch()
            if k==27:
                break
            elif k in remap.keys():
                display.addstr(y,x,'{:<5s} {:<4s}'.format(remap[k],''))
                t=invoke(display,target,remap[k])
                display.addstr(y,x,'{:<5s} {:<4s}'.format(remap[k],'ack' if t else 'nak'))
                y+=1
                y%=5
    except ():
        pass
    finally:
        curses.curs_set(True)
        display.keypad(False)
        display.clear()

if __name__=='__main__':
    os.environ.setdefault('ESCDELAY','10')
    if len(sys.argv)==2:
        curses.wrapper(functools.partial(main,sys.argv[1]))
    else:
        print('usage:\n\t{} <rokuip>'.format(sys.argv[0]))
