#!/usr/bin/env python3

import json,yaml,sys

def main():
    def do(k):
        with k as t:
            print(json.dumps(next(yaml.safe_load_all(t))))
    for f in sys.argv[1:]:
        do(open(f,'r'))
    do(sys.stdin)

if __name__=='__main__':
    main()
