set ai ts=4 sts=4 sw=4 tw=0 noet fileformat=unix
filetype plugin indent on
set modeline
set foldmethod=indent
set foldlevel=99
set hlsearch
nnoremap <space> za
"Plugin 'tmhedberg/SimpylFold'
"let g:SimpylFold_docstring_preview=1
xnoremap <Space> :!perl -wpe 'foreach my $h (/\b([0-9A-Fa-f]+?)\b/g){s/$h/@{[scalar reverse unpack("h*",pack("H*",$h))]}/}'
